### ISSUE TITLE
turning on flow linting tremendously slows down sublime

### ISSUE THREAD

**Issue by davis** [SublimeLinter/SublimeLinter-flow#19]

**Comment by whiteinge** [comment]
This is fixed by #15 (sitting for seven months) or #17 (sitting for two months); both are the same change. @ckaznocha, @NicoSantangelo is this repo still maintained? How would you feel about inviting a couple of the [fork authors](https://github.com/SublimeLinter/SublimeLinter-flow/network) as contributors here to help carry the load?

**Comment by NicoSantangelo** [comment]
I'm not currently maintaining it and I would love to hand the repo to an active maintainer.

**Comment by whiteinge** [comment]
@NicoSantangelo thank you for the prompt reply!

@RikardLegge, @xinchaobeta, @ianobermiller, @tikotzky, @cbosuna, @evenco (with apologies for the noise of a mass-ping): Please see the above invitation. Would you be interested in folding the updates you've made in your forks back here? Many hands make light work, as they say. :smile:

**Comment by ckaznocha** [comment]
Hi @whiteinge, I do indent to continue maintaining this project. Since @NicoSantangelo has lost interest I will get more active. I will merge #16 later today which resolves this issue.

**Comment by davis** [comment]
awesome! thanks everyone
