### ISSUE TITLE
flow founds errors but the linter seems to ignore

### ISSUE THREAD

**Issue by oriSomething** [SublimeLinter/SublimeLinter-flow#20]
image added
<img width="918" alt="flow" src="https://cloud.githubusercontent.com/assets/2685242/10558200/3b800842-74d0-11e5-832c-d8e45e85f95c.png">

**Comment by ckaznocha** [comment]
What version of the linter are you using? How did you install it?

**Comment by oriSomething** [comment]
i've installed it **today** from `package control`... so i guess the newest. and then `flow` version is `0.17.0` via `homebrew`

**Comment by STRML** [comment]
I'm seeing this as well.

There hasn't been a version tagged since November, so the simpler fixes (like `flow status` and the additional syntax types) aren't in the Package Control version. But even using master, I don't see any highlights.

I believe Flow syntax got much friendlier, and as a result, harder to parse.

I've been working on a new regex, but I haven't spent enough time with SublimeLinter to get it right: https://www.debuggex.com/r/3rhKU1GiwBWv4ZOk

**Comment by ckaznocha** [comment]
Looks like it will have to be updated to use the `--one-line` option

**Comment by STRML** [comment]
That doesn't really help the formatting, it just removes the line breaks.

**Comment by STRML** [comment]
On the other hand, there is JSON output, which will be way easier to deal with.

**Comment by ckaznocha** [comment]
Yeah, i think using `--jason` is probably the most reliable way to go. It means a bit of a re-write of the linter but that's probably not a bad thing. `--old-output-format` is an option too but its not as clean as grabbing the JSON.

**Comment by ckaznocha** [comment]
Closed by PR #21
